#- name: Leave Swarm if exists.
#  command: "docker swarm leave --force"
#  ignore_errors: yes
- name: 
  debug:
    msg: "[Worker] SWARM_JOIN_COMMAND_HOLDER token is {{ hostvars['SWARM_JOIN_COMMAND_HOLDER']['swarm_join_command'] }}"

- name: "Swarm Worker join"
  shell: "{{ hostvars['SWARM_JOIN_COMMAND_HOLDER']['swarm_join_command'] }}"
