- name: 
  debug:
    msg: "[Worker] SWARM_JOIN_COMMAND_HOLDER K8S token is {{ hostvars['SWARM_JOIN_COMMAND_HOLDER']['swarm_join_command'] }}"

- name: "Swarm Worker join"
  shell: "{{ hostvars['SWARM_JOIN_COMMAND_HOLDER']['swarm_join_command'] }}"
