- name: Initialize Swarm.
  command:
    docker swarm init | grep -i  'docker swarm' | grep -v manager
  register: swarm_join_command
- name: "Add Swarm worker join command to dummy host"  
  add_host:
    name:   "SWARM_JOIN_COMMAND_HOLDER"
    swarm_join_command:  "{{ swarm_join_command.stdout }}"
- name:
  debug:
    msg: "[Master] SWARM_JOIN_COMMAND_HOLDER is {{ hostvars['SWARM_JOIN_COMMAND_HOLDER']['swarm_join_command'] }}"
